import processor.Tongmuc
import processor.IIP
import processor.GDP
import processor.FDI
import processor.XNK
import processor.TMLTLP
import processor.CPI_NH_AVE
import processor.CPI_NH_YOY
import processor.CPI